version: '3.8'
services:
    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"

    productservice:
        build:
            context: .
            dockerfile: ProductService/Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - mongo
        environment:
            - MONGO_URL=${MONGO_URL}

    productwebapp:
        build:
            context: .
            dockerfile: ProductWebApp/Dockerfile
        ports:
            - "4200:4200"